spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/costControl?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: root
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
  servlet:
    multipart:
      #      enabled: true
      max-file-size: 100MB # ??? ?? ??? ??
      max-request-size: 100MB #
mail:
  address:
    admin: admin@gmail.com
jwt:
  #  key: ${JWT_SECRET_KEY}
  key: "euntaek-1234123412341234123412341234"
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420